Repository kevinlizh1992/rtterror, pull requests merged in 2022-04, with the labels that each got.

#62 customize employee_id && client details for appointment queries
  backend/__test__/employee.service.spec.ts
  backend/src/interfaces/IAppointment.ts
  backend/src/interfaces/IEmployee.ts
  backend/src/models/appointment.ts
  backend/src/models/employee.ts
  backend/src/models/syncTables.ts
  backend/src/routes/appointment.ts
  backend/src/services/appointment-service.ts
Labels: enhancement, High Priority, acceptance-test

#63 Fix/service frontend misc
  frontend/components/Layout/Drawer.js
  frontend/components/Layout/appbar.js
  frontend/components/Layout/calendar.js
  frontend/components/Layout/index.js
  frontend/components/Layout/menu.js
  frontend/components/employee/employeedetailcomponent.js
  frontend/components/employee/employeeform.js
  frontend/components/employee/index.js
  frontend/components/employee/newEmployeeDialog.js
  frontend/components/form/formComponent.js
  frontend/components/service/ConfirmDeleteDialog.js
  frontend/components/service/addServiceForm.js
  frontend/components/service/comboForm.js
  frontend/components/service/comboForm/ComboItem.js
  frontend/components/service/comboForm/EditCombo.js
  frontend/components/service/comboForm/index.js
  frontend/components/service/durationPriceDisplay.js
  frontend/components/service/durationPriceItem.js
  frontend/components/service/index.js
  frontend/components/service/serviceCardRow.js
  frontend/components/service/serviceDetailsCard.js
  frontend/next-env.d.ts
  frontend/package.json
  frontend/pages/client/index.tsx
  frontend/pages/employee/details.js
  frontend/pages/employee/index.js
  frontend/pages/service/add.js
  frontend/pages/service/details.js
  frontend/pages/service/index.js
  frontend/styles/Home.module.css
  frontend/styles/employee.module.css
  frontend/styles/layout.module.css
  frontend/styles/service.module.css
  frontend/utils/groupService.js
  frontend/yarn.lock
Labels: High Priority, acceptance-test

#70 Fix/appm calendar view
  frontend/components/appointment/AddAppointmentDialog.tsx
  frontend/components/appointment/common/generateSchedules.ts
  frontend/components/appointment/config/tuiTemplateConfig.js
  frontend/components/appointment/dropConfirmationDialog.js
  frontend/components/service/addServiceForm.js
  frontend/components/service/comboForm/index.js
  frontend/components/service/serviceDetailsCard.js
  frontend/pages/service/details.js
  frontend/pages/service/index.js
  frontend/utils/groupService.js
  frontend/yarn.lock
Labels: bug, High Priority
